// app

export const TOAST = 'TOAST'
export type TOAST = typeof TOAST

export const SHOW_LOADING = 'SHOW_LOADING'
export type SHOW_LOADING = typeof SHOW_LOADING

export const HIDE_LOADING = 'HIDE_LOADING'
export type HIDE_LOADING = typeof HIDE_LOADING

export const SHOW_MODAL = 'SHOW_MODAL'
export type SHOW_MODAL = typeof SHOW_MODAL

export const HIDE_MODAL = 'HIDE_MODAL'
export type HIDE_MODAL = typeof HIDE_MODAL

export const OPERATION_FAIL = 'OPERATION_FAIL'
export type OPERATION_FAIL = typeof OPERATION_FAIL

export const RESIZE_APP = 'RESIZE_APP'
export type RESIZE_APP = typeof RESIZE_APP

export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE'
export type SWITCH_LANGUAGE = typeof SWITCH_LANGUAGE

export const GLOBAL_TICKTIME = 'GLOBAL_TICKTIME'
export type GLOBAL_TICKTIME = typeof GLOBAL_TICKTIME

// Network

export const GET_NETWORK_METADATA = 'GET_NETWORK_METADATA'
export type GET_NETWORK_METADATA = typeof GET_NETWORK_METADATA

export const GET_NETWORK_RPC = 'GET_NETWORK_RPC'
export type GET_NETWORK_RPC = typeof GET_NETWORK_RPC

export const GET_NETWORK_REBIRTH = 'GET_NETWORK_REBIRTH'
export type GET_NETWORK_REBIRTH = typeof GET_NETWORK_REBIRTH

// block

export const GET_BLOCK_ITEM = 'GET_BLOCK_ITEM'
export type GET_BLOCK_ITEM = typeof GET_BLOCK_ITEM

export const GET_BLOCK_LIST = 'GET_BLOCK_LIST'
export type GET_BLOCK_LIST = typeof GET_BLOCK_LIST

export const GET_TOP_BLOCKS = 'GET_TOP_BLOCKS'
export type GET_TOP_BLOCKS = typeof GET_TOP_BLOCKS

// export const GET_LATEST_BLOCK = 'GET_LATEST_BLOCK'
// export type GET_LATEST_BLOCK = typeof GET_LATEST_BLOCK;

export const APPEND_LATEST_BLOCK = 'APPEND_LATEST_BLOCK'
export type APPEND_LATEST_BLOCK = typeof APPEND_LATEST_BLOCK

// transaction

export const GET_TRANSACTION_ITEM = 'GET_TRANSACTION_ITEM'
export type GET_TRANSACTION_ITEM = typeof GET_TRANSACTION_ITEM

export const GET_TRANSACTION_RECEIPT_ITEM = 'GET_TRANSACTION_RECEIPT_ITEM'
export type GET_TRANSACTION_RECEIPT_ITEM = typeof GET_TRANSACTION_RECEIPT_ITEM

export const GET_TRANSACTION_LIST = 'GET_TRANSACTION_LIST'
export type GET_TRANSACTION_LIST = typeof GET_TRANSACTION_LIST

export const GET_TOP_TRANSACTIONS = 'GET_TOP_TRANSACTIONS'
export type GET_TOP_TRANSACTIONS = typeof GET_TOP_TRANSACTIONS

export const APPEND_LATEST_TRANSACTION = 'APPEND_LATEST_TRANSACTION'
export type APPEND_LATEST_TRANSACTION = typeof APPEND_LATEST_TRANSACTION

// account
export const GET_ACCOUNT_TR_LIST = 'GET_ACCOUNT_TR_LIST'
export type GET_ACCOUNT_TR_LIST = typeof GET_ACCOUNT_TR_LIST

export const GET_ACCOUNT_ERC20_LIST = 'GET_ACCOUNT_ERC20_LIST'
export type GET_ACCOUNT_ERC20_LIST = typeof GET_ACCOUNT_ERC20_LIST

export const GET_ACCOUNT_BALANCE = 'GET_ACCOUNT_BALANCE'
export type GET_ACCOUNT_BALANCE = typeof GET_ACCOUNT_BALANCE

// const commands = ["GET_ACCOUNT_TR_LIST","GET_ACCOUNT_ERC20_LIST"]
//
// commands.forEach(function(command:string){
//   export const command = command;
//   export type command = typeof command

// })
