// app
export const TOAST = 'TOAST'

export const SHOW_LOADING = 'SHOW_LOADING'

export const HIDE_LOADING = 'HIDE_LOADING'

export const SHOW_MODAL = 'SHOW_MODAL'

export const HIDE_MODAL = 'HIDE_MODAL'

export const OPERATION_FAIL = 'OPERATION_FAIL'

export const RESIZE_APP = 'RESIZE_APP'

export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE'

export const GLOBAL_TICKTIME = 'GLOBAL_TICKTIME'

// Network
export const GET_NETWORK_METADATA = 'GET_NETWORK_METADATA'

export const GET_NETWORK_RPC = 'GET_NETWORK_RPC'

export const GET_NETWORK_REBIRTH = 'GET_NETWORK_REBIRTH'

export const GET_QUOTA_PRICE = 'GET_QUOTA_PRICE'


// block
export const GET_BLOCK_ITEM = 'GET_BLOCK_ITEM'

export const GET_BLOCK_LIST = 'GET_BLOCK_LIST'

export const GET_TOP_BLOCKS = 'GET_TOP_BLOCKS'


export const APPEND_LATEST_BLOCK = 'APPEND_LATEST_BLOCK'

// transaction
export const GET_TRANSACTION_ITEM = 'GET_TRANSACTION_ITEM'

export const GET_TRANSACTION_RECEIPT_ITEM = 'GET_TRANSACTION_RECEIPT_ITEM'

export const GET_TRANSACTION_LIST = 'GET_TRANSACTION_LIST'

export const GET_TOP_TRANSACTIONS = 'GET_TOP_TRANSACTIONS'

export const APPEND_LATEST_TRANSACTION = 'APPEND_LATEST_TRANSACTION'

// account
export const GET_ACCOUNT_TR_LIST = 'GET_ACCOUNT_TR_LIST'

export const GET_ACCOUNT_ERC20_LIST = 'GET_ACCOUNT_ERC20_LIST'

export const GET_ACCOUNT_BALANCE = 'GET_ACCOUNT_BALANCE'

export const GET_ACCOUNT_CODE = 'GET_ACCOUNT_CODE'

export const GET_ACCOUNT_ABI = 'GET_ACCOUNT_ABI'

// statics
export const GET_STATICS_PROPOSALS = 'GET_STATICS_PROPOSALS'
